name: Integration

# only trigger on pull request create and update events
on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ secrets.CACHE_BUSTER }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-${{ secrets.CACHE_BUSTER }}
            
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test

      - name: Cypress tests (headless browser)
        uses: cypress-io/github-action@v4
        with:
          command: yarn test:e2e:run
